server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
#        native:
#          search-locations: file:///Users/myounghoipark/Documents-IntelliJ/config-repo
        git: #default
          uri: https://github.com/dron512/spring-cloud-config
          default-label: main
        bootstrap: true

#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#    service-url:
#      defaultZone: http://eurekaserver:8761/eureka
#    fetch-registry: true
#    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics