# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstservice
  namespace: default
  labels:
    app: firstservice
spec:
  selector:
    matchLabels:
      app: firstservice
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: firstservice
    spec:
      containers:
      - name: firstservice
        image: parkmyounghoi/firstservice
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 1000Mi
#        livenessProbe:
#          tcpSocket:
#            port: 80
#          initialDelaySeconds: 5
#          timeoutSeconds: 5
#          successThreshold: 1
#          failureThreshold: 3
#          periodSeconds: 10
#        readinessProbe:
#          httpGet:
#            path: /_status/healthz
#            port: 80
#          initialDelaySeconds: 5
#          timeoutSeconds: 2
#          successThreshold: 1
#          failureThreshold: 3
#          periodSeconds: 10
        ports:
        - containerPort: 8081
          name: firstservice
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: firstservice
spec:
  ports:
    - nodePort: 30081
      port: 8081
      targetPort: 8081
  selector:
    app: firstservice
  type: LoadBalancer
