version: '3.8'

services:
  configserver:
    image: parkmyounghoi/configserver
    container_name: configserver
    ports:
      - "8888:8888"
    networks:
      - javamysql
  eurekaserver:
    image: parkmyounghoi/eurekaserver
    container_name: eurekaserver
    ports:
      - "8761:8761"
    networks:
      - javamysql
  firstservice:
    image: parkmyounghoi/firstservice
    container_name: firstservice
    environment:
      - spring.profiles.active=docker
    ports:
      - "8081:8081"
    networks:
      - javamysql
    depends_on:
      - eurekaserver
  secondservice:
    image: parkmyounghoi/secondservice
    container_name: secondservice
    environment:
      - spring.profiles.active=docker
    ports:
      - "8082:8082"
    networks:
      - javamysql
    depends_on:
      - eurekaserver
  apigatewayserver:
    image: parkmyounghoi/apigatewayserver
    container_name: apigatewayserver
    environment:
      - spring.cloud.config.uri=http://configserver:8888
      - spring.cloud.config.name=apigatewayserver
      - spring.profiles.active=docker
    ports:
      - "8080:8080"
    networks:
      - javamysql
#  catalogservice:
#    image: parkmyounghoi/catalogservice
#    container_name: catalogservice
#    environment:
#      - spring.cloud.config.uri=http://configserver:8888
#      - spring.cloud.config.name=catalog-service
#      - spring.profiles.active=docker
#    ports:
#      - "10002:10002"
#    networks:
#      - javamysql

  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=pmh
    ports:
      - "3306:3306"
    networks:
      - javamysql

networks:
  javamysql:
    driver: bridge
