server:
  port: 8080
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:9000/eureka
    fetch-registry: true
    register-with-eureka: true
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: first_service
          uri: lb://first-service:8081/first/**
          predicates:
            - Path=/first/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: Hi, there.
                preLogger: true
                postLogger: true
        - id: second_service
          uri: http://localhost:8082/second/**
          predicates:
            - Path=/second/**
          filters:
            - AddRequestHeader=Req-first-Header, second
            - AddResponseHeader=Res-first-Header, second
            - name: CustomFilter
        - id: user_service
          uri: lb://user-service:8083/user-service/**
          predicates:
            - Path=/user-service/**
          filters:
            - AddRequestHeader=Req-first-Header, second
            - AddResponseHeader=Res-first-Header, second
            - name: CustomFilter

